### ISSUE TITLE
Checkpoint loading into cuda device

### ISSUE THREAD

**Issue by zzowenzz** [jhl-Det/RGBD_Video_SOD#1]
Hi @jhl-Det, Thanks for open-sourcing this incredible work. Just one issue is that the provided pre-trained model is based on an MPS device, and it's better to have one that can be directly implemented in Pytorch for the Cuda device. Currently, I need to convert to CPU first and then move the loaded model to Cuda.

The following question is: can you provide a script to extract a Salient image from an input image?

**Comment by jhl-Det** [comment]
Thanks for following our work. Due to unforeseen circumstances, our CUDA devices (NVIDIA GeForce RTX 2080 Ti as mentioned in the paper) are no longer available. Therefore, we utilized the M3 Max chip to reproduce our results. However, the model trained on MPS devices is still compatible with CUDA devices, albeit with potentially increased I/O times.

Currently, our model is designed to extract saliency maps from RGB-D videos. You can use state-of-the-art methods, such as [SP-Net](https://github.com/taozh2017/SPNet) to extract a salient image from an input image.
